FROM node:18.9.0-alpine

ARG production

ENV INSTALL_PATH /app

COPY frontend/package.json frontend/yarn.lock /tmp/
RUN cd /tmp && yarn install $(if [[ ! -z $production ]]; then echo "--production"; fi) \
  && mkdir -p ${INSTALL_PATH} \
  && cd ${INSTALL_PATH} \
  && cp -R /tmp/node_modules ${INSTALL_PATH} \
  && rm -r /tmp/* && yarn cache clean

WORKDIR ${INSTALL_PATH}

COPY frontend .
COPY backend/testutils/testdata/test-cases.json src/testutils/backend-testdata/test-cases.json
COPY backend/testutils/testdata/golden src/testutils/backend-testdata/golden

EXPOSE 3000

CMD ["yarn", "start"]
