version: "3.9"

services:
  backend:
    build: 
      context: backend/
    ports:
      - "8080:8080"
    networks:
      - resolve-net
    # volumes: 
    #   - ./backend:/app

  backend-debug:
    build:
      context: backend/
      dockerfile: Dockerfile.debug
    cap_add:
      - SYS_PTRACE
    ports:
      - "2345:2345"
      - "8080:8080"
    networks:
      - resolve-net
    security_opt:
      - apparmor:unconfined
    # volumes:
    #   - ./backend:/app

  gotest:
    build: 
      context: backend/
      dockerfile: Dockerfile.test
    command: ["go","test","-cover","./..."]
    volumes:
      - ./backend:/app

  gocover:
    build: 
      context: backend/
      dockerfile: Dockerfile.test
    command: 
      - /bin/sh
      - -c
      - |
        go test -coverprofile=coverage.out ./... &&
        go tool cover -func=coverage.out
        # go tool cover -html=coverage.out
    volumes:
      - ./backend:/app

networks:
  resolve-net:
    driver: bridge