version: "3.9"

x-build-frontend: &x-build-frontend
  image: resolve-frontend
  build:
    context: frontend/
    cache_from:
      - resolve-frontend
  networks:
    - resolve-net
  depends_on:
    - backend

x-development-volumes-frontend: &x-development-volumes-frontend
  volumes:
    - ./frontend:/app


services:
  frontend:
    <<: *x-build-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/v0/
    <<: *x-development-volumes-frontend

  frontend-test:
    <<: *x-build-frontend
    command: yarn test
    environment:
      - REACT_APP_API_URL=http://backend:8080/v0/
    <<: *x-development-volumes-frontend

  backend:
    build:
      context: backend/
    ports:
      - "8080:8080"
    networks:
      - resolve-net
    # volumes:
    #   - ./backend:/app

  backend-debug:
    build:
      context: backend/
      # See file header comment in Dockerfile.debug-and-test
      dockerfile: Dockerfile.debug-and-test
    # Dockerfile.debug-and-test is primarily a test container.  We need to override
    # the `go test...` CMD, running delve instead.
    command: [ "./tools/dlv", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./resolve" ]
    cap_add:
      - SYS_PTRACE
    ports:
      # Delve port
      - "2345:2345"
      # Application port
      - "8080:8080"
    networks:
      - resolve-net
    security_opt:
      - apparmor:unconfined
    # volumes:
    #   - ./backend:/app

  backend-test:
    build:
      context: backend/
      # See file header comment in Dockerfile.debug-and-test
      dockerfile: Dockerfile.debug-and-test
    command: ["go","test","-cover","./..."]
   # volumes:
   #   - ./backend:/app

  backend-test-coverage:
    build:
      context: backend/
      dockerfile: Dockerfile.debug-and-test
    command:
      - /bin/sh
      - -c
      - |
        go test -coverprofile=coverage.out ./... &&
        go tool cover -func=coverage.out
        # go tool cover -html=coverage.out
    # volumes:
    #  - ./backend:/app

networks:
  resolve-net:
    driver: bridge
