version: "3.9"

services:
  backend:
    build: 
      context: backend/
    ports:
      - "8080:8080"
    networks:
      - getit-net
    # volumes: 
    #   - ./:/app

  gotest:
    build: 
      context: backend/
      dockerfile: Dockerfile.test
    command: ["go","test","./..."]
    volumes:
      - ./:/app

networks:
  getit-net:
    driver: bridge