version: 2.1

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io

docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:20.10.6-dc-1.29.1-0
  working_directory: ~/app

commands:
  tag-images-and-push-to-quay:
    description: Tag "latest", git branch, and git branch + git commit SHA1
    parameters:
      image:
        type: string
    steps:
      - <<: *auth_quay
      - run:
          name: Tag images and push to Quay
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker tag << parameters.image >> quay.io/nyulibraries/<< parameters.image >>:latest
            docker tag << parameters.image >> quay.io/nyulibraries/<< parameters.image >>:${BRANCH_NO_SLASH}
            docker tag << parameters.image >> quay.io/nyulibraries/<< parameters.image >>:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker push quay.io/nyulibraries/<< parameters.image >>:latest
            docker push quay.io/nyulibraries/<< parameters.image >>:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/<< parameters.image >>:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

jobs:
  frontend-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build frontend-test service
          command: |
            docker-compose build frontend-test
      - run:
          name: Run tests
          command: |
            docker-compose run frontend-test
      - tag-images-and-push-to-quay:
          image: "ariadne_frontend_test"

  frontend-build:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build frontend service
          command: |
            docker-compose build frontend
      - tag-images-and-push-to-quay:
          image: "ariadne_frontend"

  backend-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build backend-test service
          command: |
            docker-compose build backend-test
      - run:
          name: Check formatting
          command: |
            gofmt_result="$( docker-compose run backend-test /bin/bash -c 'export APP_PATH=/app/; if [[ ! -z $( find $APP_PATH -name "*.go\
            " ) ]]; then gofmt -l $APP_PATH; else echo >&2 "No *.go files found in path: $APP_PATH"; fi' )"

            # Even if `gofmt -l $APP_PATH` returns no paths, there still seem to
            # be some non-printing characters in `gofmt_result` (in CircleCI output,
            # they appear as "^@" characters), so instead of doing a `test -z` test,
            # simply check for the presence of alphanumeric characters, which
            # would only be present in the output if `gofmt` returned paths or
            # if an error occurred.
            if [[ "$gofmt_result" =~ [[:alnum:]] ]]
            then
                echo -e "\n\ngofmt check fail:\n$gofmt_result"
                exit_status=1
            else
                exit_status=0
            fi

            exit $exit_status
      - run:
          name: Run tests
          command: |
            docker-compose run backend-test
      - tag-images-and-push-to-quay:
          image: "ariadne_backend_test"

  backend-build:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build backend service
          command: |
            docker-compose build backend
      - tag-images-and-push-to-quay:
          image: "ariadne_backend"
  e2e:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build e2e-test service
          command: |
            docker-compose build e2e
      - run:
          name: Run tests
          command: |
            docker-compose run e2e
      - tag-images-and-push-to-quay:
          image: "ariadne_e2e"

workflows:
  version: 2.1
  frontend-test-and-build:
    jobs:
      - frontend-test
      - frontend-build:
          requires:
            - frontend-test
  backend-test-and-build:
    jobs:
      - backend-test
      - backend-build:
          requires:
            - backend-test
  e2e:
    jobs:
      - e2e
