version: 2.1

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io

docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:20.10.6-dc-1.29.1-0
  working_directory: ~/app

commands:
  tag-images-and-push-to-quay:
    description: Tag "latest", git branch, and git branch + git commit SHA1
    steps:
      - <<: *auth_quay
      - run:
          name: Tag images and push to Quay
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker tag resolve quay.io/nyulibraries/resolve:latest
            docker tag resolve quay.io/nyulibraries/resolve:${BRANCH_NO_SLASH}
            docker tag resolve quay.io/nyulibraries/resolve:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}
            docker push quay.io/nyulibraries/resolve:latest
            docker push quay.io/nyulibraries/resolve:${BRANCH_NO_SLASH}
            docker push quay.io/nyulibraries/resolve:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

jobs:
  backend-test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build backend-test service
          command: |
            docker-compose build backend-test
      - run:
          name: Check formatting
          command: |
            gofmt_result="$( docker-compose run backend-test /bin/bash -c 'export APP_PATH=/app/; if [[ ! -z $( find $APP_PATH -name "*.go\
            " ) ]]; then gofmt -l $APP_PATH; else echo >&2 "No *.go files found in path: $APP_PATH"; fi' )"

            if [ -z "$gofmt_result" ]
            then
                check_formatting_exit_status=0
            else
                echo -e "gofmt check fail:\n$gofmt_result"
                check_formatting_exit_status=1
            fi

            exit $check_formatting_exit_status
      - run:
          name: Run tests
          command: |
            docker-compose run backend-test
# Don't tag and push to Quay until we decide upon a (semi-)permanent repository name.
#      - tag-images-and-push-to-quay

  backend-build:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build backend service
          command: |
            docker-compose build backend
# Don't tag and push to Quay until we decide upon a (semi-)permanent repository name.
#      - tag-images-and-push-to-quay

workflows:
  backend-test-and-build:
    jobs:
      - backend-test
      - backend-build:
          requires:
            - backend-test
